### ISSUE TITLE
Simple error in documentation

### ISSUE THREAD

**Issue by brenoh97** [eclipse-tocandira/Tocandira#13]
In Tocandira readme.dm, the session  **_Our Motivations_** contains an error in the sentence below in second paragraph:

_"While the IT world has a lot of companies investing in open source development with robust applications built on top of them with years of stable operation and continuous improvement of the operational technologies in industrial plants are becoming outdated and useless."_

New sentence suggestion for better understanding:

"While the IT world has a lot of companies investing in open source development with robust applications built on top of them with years of stable operation and continuous improvement of the operational technologies **(,)** in industrial plants **they** are becoming outdated and useless."

**Comment by pedro-ricardo** [comment]
fixed in #14
